import React from 'react';
import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer';
import { TripSettlementSummary, TripTransaction } from '../../hooks/useTripSettlement';

const styles = StyleSheet.create({
    page: {
        padding: 30,
        fontFamily: 'Helvetica',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#e2e8f0',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1e3a8a', // blue-900
    },
    subtitle: {
        fontSize: 12,
        color: '#64748b',
        marginTop: 4,
    },
    summaryBlock: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: '#f8fafc',
        padding: 15,
        borderRadius: 8,
        marginBottom: 20,
    },
    summaryItem: {
        alignItems: 'center',
    },
    summaryLabel: {
        fontSize: 10,
        color: '#64748b',
        textTransform: 'uppercase',
    },
    summaryValue: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#0f172a',
        marginTop: 4,
    },
    balanceValue: (isOwing: boolean) => ({
        fontSize: 16,
        fontWeight: 'bold',
        color: isOwing ? '#dc2626' : '#16a34a',
        marginTop: 4,
    }),
    table: {
        width: '100%',
        marginTop: 10,
    },
    tableHeader: {
        flexDirection: 'row',
        backgroundColor: '#f1f5f9',
        borderBottomWidth: 1,
        borderBottomColor: '#cbd5e1',
        padding: 8,
    },
    tableHeaderCell: {
        fontSize: 10,
        fontWeight: 'bold',
        color: '#475569',
    },
    tableRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
        padding: 8,
    },
    tableCell: {
        fontSize: 10,
        color: '#334155',
    },
    colDate: { width: '20%' },
    colCategory: { width: '25%' },
    colDetails: { width: '35%' },
    colAmount: { width: '20%', textAlign: 'right' },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 30,
        right: 30,
        textAlign: 'center',
        fontSize: 8,
        color: '#94a3b8',
        borderTopWidth: 1,
        borderTopColor: '#e2e8f0',
        paddingTop: 10,
    }
});

interface TourSettlementPDFProps {
    settlement: TripSettlementSummary;
    driverName: string;
    agencyName: string;
}

export const TourSettlementPDF = ({ settlement, driverName, agencyName }: TourSettlementPDFProps) => {
    const formatDate = (timestamp: any) => {
        if (!timestamp) return 'N/A';
        // Handle both Firestore Timestamp and regular Date objects
        const date = timestamp.toDate ? timestamp.toDate() : new Date(timestamp);
        return date.toLocaleDateString();
    };

    const formatCurrency = (cents: number) => {
        return `LKR ${(cents / 100).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    };

    const isDriverOwing = settlement.balanceDueLKR > 0;

    return (
        <Document>
            <Page size="A4" style={styles.page}>

                {/* Header */}
                <View style={styles.header}>
                    <View>
                        <Text style={styles.title}>Final Driver Settlement</Text>
                        <Text style={styles.subtitle}>Generated by TourTracksy</Text>
                        <Text style={styles.subtitle}>Date: {new Date().toLocaleDateString()}</Text>
                    </View>
                    <View style={{ alignItems: 'flex-end' }}>
                        <Text style={{ fontSize: 14, fontWeight: 'bold' }}>{agencyName}</Text>
                        <Text style={styles.subtitle}>Driver: {driverName}</Text>
                        <Text style={styles.subtitle}>Trip Ref: {settlement.tripId}</Text>
                    </View>
                </View>

                {/* Summary Block */}
                <View style={styles.summaryBlock}>
                    <View style={styles.summaryItem}>
                        <Text style={styles.summaryLabel}>Agency Advance</Text>
                        <Text style={styles.summaryValue}>{formatCurrency(settlement.agencyAdvanceLKR)}</Text>
                    </View>
                    <View style={styles.summaryItem}>
                        <Text style={styles.summaryLabel}>Total Expenses</Text>
                        <Text style={styles.summaryValue}>{formatCurrency(settlement.totalExpensesLKR)}</Text>
                    </View>
                    <View style={styles.summaryItem}>
                        <Text style={styles.summaryLabel}>Final Balance</Text>
                        <Text style={styles.balanceValue(isDriverOwing)}>
                            {isDriverOwing
                                ? `Refund to Agency: ${formatCurrency(settlement.balanceDueLKR)}`
                                : `Due to Driver: ${formatCurrency(Math.abs(settlement.balanceDueLKR))}`}
                        </Text>
                    </View>
                </View>

                {/* Itemized Expenses Table */}
                <View style={styles.table}>
                    <View style={styles.tableHeader}>
                        <Text style={[styles.tableHeaderCell, styles.colDate]}>Date</Text>
                        <Text style={[styles.tableHeaderCell, styles.colCategory]}>Category</Text>
                        <Text style={[styles.tableHeaderCell, styles.colDetails]}>Payment Source</Text>
                        <Text style={[styles.tableHeaderCell, styles.colAmount]}>Amount (LKR)</Text>
                    </View>

                    {settlement.transactions.map((txn, idx) => (
                        txn.type === 'expense' && (
                            <View key={idx} style={styles.tableRow}>
                                <Text style={[styles.tableCell, styles.colDate]}>{formatDate(txn.createdAt)}</Text>
                                <Text style={[styles.tableCell, styles.colCategory]}>{txn.category}</Text>
                                <Text style={[styles.tableCell, styles.colDetails]}>
                                    {txn.paid_by === 'agency_advance' ? 'From Advance' : 'Out of Pocket'}
                                    {txn.currency !== 'LKR' ? ` (${(txn.amount_cents / 100).toFixed(2)} ${txn.currency})` : ''}
                                </Text>
                                <Text style={[styles.tableCell, styles.colAmount]}>
                                    {formatCurrency(txn.lkr_value_cents)}
                                </Text>
                            </View>
                        )
                    ))}
                </View>

                {/* Footer */}
                <View style={styles.footer}>
                    <Text>This is a computer-generated document. TourTracksy Financial OS for Tourism.</Text>
                </View>

            </Page>
        </Document>
    );
};
